//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_history
    {
        public int IdOrderHistory { get; set; }
        public int IdOrder { get; set; }
        public System.DateTime DateOrder { get; set; }
        public long PriceTotal { get; set; }
    
        public virtual order_details order_details { get; set; }
    }
}
