//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_details()
        {
            this.order_history = new HashSet<order_history>();
        }
    
        public int IdOrder { get; set; }
        public int IdFood { get; set; }
        public int Amount { get; set; }
        public long PriceFood { get; set; }
        public int IdClient { get; set; }
        public string Comments { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual foods foods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_history> order_history { get; set; }
    }
}
