SET IDENTITY_INSERT [dbo].[Food] ON
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (1, N'Margheritta', 20)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (2, N'Vegetariana', 22)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (3, N'Tosca', 25)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (4, N'Venecia', 25)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (5, N'Double_Cheese', 2)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (6, N'Salami', 2)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (7, N'Ham', 2)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (8, N'Mushrooms', 2)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (9, N'Tomato_soup', 12)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (10, N'Chicken_soup', 10)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (11, N'Schnitzel_chips', 30)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (12, N'Schnitzel_rice', 30)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (13, N'Schnitzel_potatoes', 30)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (14, N'Fish_chips', 28)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (15, N'Hungarian_Cake', 27)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (16, N'Salad_bar', 7)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (17, N'Set_sauces', 5)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (18, N'Coffee', 5)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (19, N'Tea', 5)
INSERT INTO [dbo].[Food] ([IdFood], [FoodName], [Price]) VALUES (20, N'Cola', 5)
SET IDENTITY_INSERT [dbo].[Food] OFF
